
USE M7_BI
GO


DROP VIEW IF EXISTS Debt_Reporting.V_Debt_Management_Data_Current
GO

CREATE VIEW 
-- SELECT * FROM
Debt_Reporting.V_Debt_Management_Data_Current

AS

/*

The SQL code for this View is generated by a Stored Procedure held in the Portal DB

    EXEC AZURE_PORTAL_DEV.M7_Portal_DEV.[app_master_data].[SP_Attribute_Values_Pivot] 'DEBT'

*/


SELECT 
  * 
FROM 
  (
    SELECT 
        Tag = CAST( tag as nvarchar(50))
      , entity_id = CAST( entity_id as int ) 
      , [Amortisation] = CAST ( [Amortisation] as nvarchar(max)) 
      , [Beneficiary] = CAST ( [Beneficiary] as nvarchar(max))
      , [Borrowers] = CAST ( [Borrowers] as nvarchar(max))
      , [CAP] = CAST ( [CAP] as NUMERIC(19,6) )   -- ! best guess! 

      , [Country] = CAST ( [Country]  AS nvarchar(50))
      
      , [CT_DSCR_(LF & B) ] = CAST ( [CT_DSCR_(LF & B) ] AS numeric(19,4) )  -- ! total guess, no values to base this on 
      
      , [CT_Historic_Debt_Yield] = CAST ( [CT_Historic_Debt_Yield] AS numeric(19,4) )  
      , [CT_Historic_DSCR] = CAST ( [CT_Historic_DSCR] AS numeric(19,4) )  
      , [CT_Historic_ICR] = CAST ( [CT_Historic_ICR] AS numeric(19,4) )  
      , [CT_LTV] = CAST ( [CT_LTV] AS numeric(19,4) )  
      , [CT_NRI] = CAST ( [CT_NRI] AS numeric(19,4) )  
      , [CT_Projected_Debt_Yield] = CAST ( [CT_Projected_Debt_Yield] AS numeric(19,4) )  
      , [CT_Projected_DSCR] = CAST ( [CT_Projected_DSCR] AS numeric(19,4) )  
      , [CT_Projected_ICR] = CAST ( [CT_Projected_ICR] AS numeric(19,4) )  
      
      , [Currency] = CAST ( [Currency] as nvarchar(5) )

      , [Current_Loan_Amount] = CAST ( [Current_Loan_Amount] AS numeric(19,4))
      , [Current_LTV] = CAST ( [Current_LTV] AS numeric(19,4))
      , [Current_Valuation] = CAST ( [Current_Valuation] AS numeric(19,4))
      , [D_DSCR_(LF & B) ] = CAST ( [D_DSCR_(LF & B) ] AS numeric(19,4)) 

      , [D_Historic_Debt_Yield] = CAST ( [D_Historic_Debt_Yield] AS numeric(19,4)) 
      , [D_Historic_DSCR] = CAST ( [D_Historic_DSCR] AS numeric(19,4)) 
      , [D_Historic_ICR] = CAST ( [D_Historic_ICR] AS numeric(19,4)) 
      , [D_LTV] = CAST ( [D_LTV] AS numeric(19,4)) 
      , [D_NRI] = CAST ( [D_NRI] AS numeric(19,4)) 
      , [D_Projected_Debt_Yield] = CAST ( [D_Projected_Debt_Yield] AS numeric(19,4)) 
      , [D_Projected_DSCR] = CAST ( [D_Projected_DSCR] AS numeric(19,4)) 
      , [D_Projected_ICR] = CAST ( [D_Projected_ICR] AS numeric(19,4)) 

      , [Debt_Type] = CAST ( [Debt_Type] as nvarchar(40) ) 

      , [Drawdown_LTV] = CAST ( [Drawdown_LTV]  AS numeric(19,4) )
      , [Drawdown_Valuation] = CAST ( [Drawdown_Valuation] as BIGINT) 
      , [Extension_Options] = CAST ( [Extension_Options] as nvarchar(40) ) 
      , [Floating_Rate] = CAST ( [Floating_Rate] as nvarchar(40) ) 
      , [Hard_Covenant] = CAST ( [Hard_Covenant] as nvarchar(40) ) 

      , [Hedge_Expiry_Date] = CAST ( [Hedge_Expiry_Date] as date ) 
      , [Initial_Expiry_date] = CAST ( [Initial_Expiry_date] as date ) 
      , [Interest_Payment_Date] = CAST ( [Interest_Payment_Date] as nvarchar(max)) 

      , [IPD] = CAST ( [IPD] AS nvarchar(50) )

      , [Last_Valuation_Date] = CAST ( [Last_Valuation_Date] as date) 
      , [Lender] = CAST ( [Lender] AS nvarchar(max))

      , [Likely_Required_Paydown] = CAST ( [Likely_Required_Paydown] as numeric(19,4) ) 
       , [Likely_Valuation_Date] = CAST ( [Likely_Valuation_Date] as date)
      , [Loan_Start_Date] = CAST ( [Loan_Start_Date] as date ) 
      , [Margin] = CAST ( [Margin] as nvarchar(50)) -- ! This one doesn't feel like it should be text... Has values like "3.06% (Blended)" and "Facility A - 2.55% (Fixed) Facility B - 2.50% (Floating)", otherwise this could be numeric

      , [Next_Maturity_Date]  = CAST ( [Next_Maturity_Date] as date)

      , [Original_Loan_Amount] = CAST ( [Original_Loan_Amount] as bigint) 
      
      , [Portfolio] = CAST ( [Portfolio] as nvarchar(max))

      , [Prepayment_Fees] = CAST ( [Prepayment_Fees] as nvarchar(max)) -- ! Name of field suggests numeric, but all text

      , [Principal_Hedged] = CAST ( [Principal_Hedged]  AS bigint )

      , [R_DSCR_(LF & B) ] = CAST ( [R_DSCR_(LF & B) ] AS numeric(19,4) )  -- ! total guess, no values to base this on 
      
      , [R_Historic_Debt_Yield] = CAST ( [R_Historic_Debt_Yield] as numeric(19,4) ) 
      , [R_Historic_DSCR] = CAST ( [R_Historic_DSCR] as numeric(19,4) ) 
      , [R_Historic_ICR] = CAST ( [R_Historic_ICR] as numeric(19,4) ) 
      , [R_LTV] = CAST ( [R_LTV] as numeric(19,4) ) 
      , [R_NRI] = CAST ( [R_NRI] as numeric(19,4) ) 
      , [R_Projected_Debt_Yield] = CAST ( [R_Projected_Debt_Yield] as numeric(19,4) ) 
      , [R_Projected_DSCR] = CAST ( [R_Projected_DSCR] as numeric(19,4) ) 
      , [R_Projected_ICR] = CAST ( [R_Projected_ICR] as numeric(19,4) ) 

      , [Release_Price_over_ALA] = CAST ( [Release_Price_over_ALA] as nvarchar(max) ) -- ! feels like it should be numeric... 
      
      , [Soft_Covenant] = CAST ( [Soft_Covenant] as numeric(19,4) )
      , [SWAP] = CAST ( [SWAP] as numeric(19,4) ) 
      , [Total_Rate_As_At_IPD] = CAST ( [Total_Rate_As_At_IPD] as numeric(19,4) )

    from 
      (
        SELECT 
          tag, 
          attribute = REPLACE(attribute, ' ', '_'), 
          [entity_id], 
          entity_tag_value 
        FROM 
          [AZURE_PORTAL_DEV].[M7_Portal_DEV].[app_master_data].[v_attribute_values_DEBT] AS V 

        WHERE 
          multi_record = 0 
          and 
          /* ENTITY ID */
          [entity_id] = 0 
          OR 0 = 0 
        UNION 
        SELECT 
          tag, 
          attribute = REPLACE(attribute, ' ', '_'), 
          [entity_id], 
          entity_tag_value = STRING_AGG(entity_tag_value, ', ') 
        FROM 
          (
            SELECT 
              *, 
              [multi_record_count] = count(*) over (partition by entity_id, attribute) 
            FROM 
              [AZURE_PORTAL_DEV].[M7_Portal_DEV].[app_master_data].[v_attribute_values_DEBT] 
            WHERE 
              multi_record = 1
          ) AS V 
        WHERE 
          multi_record_count > 1 
          AND 
          /* ENTITY ID */
          [entity_id] = 0 
          OR 0 = 0 
        GROUP BY 
          tag, 
          entity_id, 
          ATTRIBUTE
      ) X PIVOT (
        MAX(entity_tag_value) for ATTRIBUTE in (
          [Amortisation], 
          [Beneficiary], 
          [Borrowers], 
          [CAP], 
          [Country], 
          [CT_DSCR_(LF & B) ], 
          [CT_Historic_Debt_Yield], 
          [CT_Historic_DSCR], 
          [CT_Historic_ICR], 
          [CT_LTV], 
          [CT_NRI], 
          [CT_Projected_Debt_Yield], 
          [CT_Projected_DSCR], 
          [CT_Projected_ICR], 
          [Currency], 
          [Current_Loan_Amount], 
          [Current_LTV], 
          [Current_Valuation], 
          [D_DSCR_(LF & B) ], 
          [D_Historic_Debt_Yield], 
          [D_Historic_DSCR], 
          [D_Historic_ICR], 
          [D_LTV], 
          [D_NRI], 
          [D_Projected_Debt_Yield], 
          [D_Projected_DSCR], 
          [D_Projected_ICR], 
          [Debt_Type], 
          [Drawdown_LTV], 
          [Drawdown_Valuation], 
          [Extension_Options], 
          [Floating_Rate], 
          [Hard_Covenant], 
          [Hedge_Expiry_Date], 
          [Initial_Expiry_date], 
          [Interest_Payment_Date], 
          [IPD], 
          [Last_Valuation_Date], 
          [Lender], 
          [Likely_Required_Paydown], 
          [Likely_Valuation_Date], 
          [Loan_Start_Date], 
          [Margin], 
          [Next_Maturity_Date], 
          [Original_Loan_Amount], 
          [Portfolio], 
          [Prepayment_Fees], 
          [Principal_Hedged], 
          [R_DSCR_(LF & B) ], 
          [R_Historic_Debt_Yield], 
          [R_Historic_DSCR], 
          [R_Historic_ICR], 
          [R_LTV], 
          [R_NRI], 
          [R_Projected_Debt_Yield], 
          [R_Projected_DSCR], 
          [R_Projected_ICR], 
          [Release_Price_over_ALA], 
          [Soft_Covenant], 
          [SWAP], 
          [Total_Rate_As_At_IPD]
        )
      ) P1
  ) X 

