
DROP VIEW IF EXISTS Debt_Reporting.V_Debt_Management_Data_View
GO

CREATE VIEW 
-- select * from
Debt_Reporting.V_Debt_Management_Data_View
AS
SELECT 
        ID
        ,[DateTime_Record_Captured]
        ,current_record
        ,[Is_Month_End_Date]

		,[Tag]
		,[entity_id]
		,[Amortisation]
		,[Beneficiary]
		,[Borrowers]
		,[CAP]
		,[Country]
		,[CT_DSCR_(LF & B) ]
		,[CT_Historic_Debt_Yield]
		,[CT_Historic_DSCR]
		,[CT_Historic_ICR]
		,[CT_LTV]
		,[CT_NRI]
		,[CT_Projected_Debt_Yield]
		,[CT_Projected_DSCR]
		,[CT_Projected_ICR]
		,[Currency]
		,[Current_Loan_Amount]
		,[Current_LTV]
		,[Current_Valuation]
		,[D_DSCR_(LF & B) ]
		,[D_Historic_Debt_Yield]
		,[D_Historic_DSCR]
		,[D_Historic_ICR]
		,[D_LTV]
		,[D_NRI]
		,[D_Projected_Debt_Yield]
		,[D_Projected_DSCR]
		,[D_Projected_ICR]
		,[Debt_Type]
		,[Drawdown_LTV]
		,[Drawdown_Valuation]
		,[Extension_Options]
		,[Floating_Rate]
		,[Hard_Covenant]
		,[Hedge_Expiry_Date]
		,[Initial_Expiry_date]
		,[Interest_Payment_Date]
		,[IPD]
		,[Last_Valuation_Date]
		,[Lender]
		,[Likely_Required_Paydown]
		,[Likely_Valuation_Date]
		,[Loan_Start_Date]
		,[Margin]
		,[Next_Maturity_Date]
		,[Original_Loan_Amount]
		,[Portfolio]
		,[Prepayment_Fees]
		,[Principal_Hedged]
		,[R_DSCR_(LF & B) ]
		,[R_Historic_Debt_Yield]
		,[R_Historic_DSCR]
		,[R_Historic_ICR]
		,[R_LTV]
		,[R_NRI]
		,[R_Projected_Debt_Yield]
		,[R_Projected_DSCR]
		,[R_Projected_ICR]
		,[Release_Price_over_ALA]
		,[Soft_Covenant]
		,[SWAP]
		,[Total_Rate_As_At_IPD]
FROM [Debt_Reporting].[Debt_Management_Data]